### ISSUE TITLE
GrSciColl mapping

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-uk-collections#2]
https://uk-collections.hp.gbif-staging.org/specimen/search?entity=2600396602

That record is published by [Marine Biological Association
](https://www.gbif.org/publisher/f6b48504-1651-4a49-a88d-c2bc6178694d)

The institutionCode for the occurrence is MBA, which match an Australian institution that use that code, and so it is being matched to that. There is no institution that look to be [Marine Biological Association
](https://www.gbif.org/publisher/f6b48504-1651-4a49-a88d-c2bc6178694d)

In this case that means that the specimen search includes data that are not being matched to any of the institutions or collections in UK.

This should be fixed either by 
* data cleaning or
* find another way to restrict the specimen scope (one way could be by the list of institutions instead of the current specimens published by UK with a match institution, but I'm not sure how it would perform)

**Comment by lmfrench** [comment]
Thanks for spotting this. We will ultimately want to fix this by data cleaning, but we may temporarily restrict the specimen scope by a list of institutions in order to launch a 'beta' version of the portal. This will depend on how much data cleaning we need to do: we got access to grscicoll today, so we will assess this over the next couple of weeks.

**Comment by lmfrench** [comment]
Marie & Tara have now fixed this
