### ISSUE TITLE
Edit search on homepage

### ISSUE THREAD

**Issue by TaraWainwright** [gbif/hp-uk-collections#43]
For further discussion. To emphasise the data aspect on the homepage.

A search bar on homepage similar to the NHM portal where people can choose to search specimens or institutions, rather than having buttons to direct to the respective pages.

Film either underneath the search section or side by side.

**Comment by MortenHofft** [comment]
This is not part of the theme, but can easily be implemented with custom html and possibly some javascript.

https://beaty-biodiversity-museum.hp.gbif-staging.org/ have done something similar.

For autocomplete on species names in the backbone we have a suggest API
https://techdocs.gbif.org/en/openapi/v1/species#/Searching%20names/suggestNames - then you could use the taxonKey parameter instead of free text search.
